{ config, lib, inputs, ... }:

# Helium (a Chromium-based browser), themed with a Chrome theme generated
# from the caelestia scheme and loaded unpacked on every start.
#
# Not caelestia's own Chromium approach (a BrowserThemeColor policy):
# Chrome turns a policy colour into an auto-generated theme and clamps its
# lightness, so even the scheme's darkest surface as the seed gave a frame
# of about rgb(81,42,42), far lighter than caelestia's near-black. A theme
# sets exact colours. Trade-offs: Chrome reads themes only at startup, so a
# scheme change shows on Helium's next start; and themes have no accent
# slot, so focus rings and buttons keep Chrome's blue.
let
  heliumThemeDir = "${config.xdg.stateHome}/caelestia/helium-theme";

  # The theme's manifest.json, as a caelestia template. Chrome wants colours
  # as [r, g, b] arrays, hence .red/.green/.blue. The version is built from
  # a few colours, so a scheme change looks like a theme update to Chrome.
  heliumThemeTemplate = let
    rgb = c: "[{{ ${c}.red }}, {{ ${c}.green }}, {{ ${c}.blue }}]";
    # Chrome theme slot -> caelestia scheme colour. Same layering as
    # caelestia's own surfaces: frame darkest-but-one, toolbar/omnibox a
    # step up each, the new tab page the base surface.
    slots = {
      frame = "surfaceContainer";
      frame_inactive = "surfaceContainer";
      frame_incognito = "surfaceContainer";
      frame_incognito_inactive = "surfaceContainer";
      toolbar = "surfaceContainerHigh";
      toolbar_text = "onSurface";
      toolbar_button_icon = "onSurfaceVariant";
      tab_text = "onSurface";
      tab_background_text = "onSurfaceVariant";
      tab_background_text_inactive = "onSurfaceVariant";
      bookmark_text = "onSurface";
      omnibox_background = "surfaceContainerHighest";
      omnibox_text = "onSurface";
      button_background = "surfaceContainerHighest";
      ntp_background = "surface";
      ntp_text = "onSurface";
      ntp_link = "primary";
      ntp_header = "primary";
    };
  in ''
    {
      "manifest_version": 3,
      "name": "Caelestia",
      "description": "Generated by the caelestia CLI from the current scheme.",
      "version": "{{ surfaceContainer.hue }}.{{ surfaceContainer.lightness }}.{{ primary.hue }}.{{ primary.lightness }}",
      "theme": {
        "colors": {
          ${lib.concatStringsSep ",\n      " (lib.mapAttrsToList (slot: c: ''"${slot}": ${rgb c}'') slots)}
        }
      }
    }
  '';
in
{
  imports = [ inputs.helium-browser.homeModules.default ];

  programs.helium = {
    enable = true;
    flags = [ "--load-extension=${heliumThemeDir}" ];
  };

  # caelestia's Chromium integration writes a BrowserThemeColor policy (into
  # /etc, with `sudo -n tee`), which would override this theme ("blocked by
  # the administrator") — and it only knows chromium/brave/chrome anyway.
  programs.caelestia.cli.settings.theme.enableChromium = false;

  # The CLI renders templates into ~/.local/state/caelestia/theme, but
  # Chrome needs a directory of its own with the file named manifest.json,
  # and writes its compiled copy ("Cached Theme.pak") next to it. So that
  # directory is a real one, with only the manifest linked in.
  xdg.configFile."caelestia/templates/helium-theme.json".text = heliumThemeTemplate;
  xdg.stateFile."caelestia/helium-theme/manifest.json".source =
    config.lib.file.mkOutOfStoreSymlink "${config.xdg.stateHome}/caelestia/theme/helium-theme.json";

  # Chrome only rebuilds its compiled copy when the theme version changes,
  # and the version only covers a few colours, so a scheme differing
  # elsewhere could keep the stale one. Deleting it after every render makes
  # the next start always rebuild: after activation here, and after scheme
  # changes through postHooks.
  home.activation.clearHeliumThemeCache = lib.hm.dag.entryAfter [ "renderCaelestiaTemplates" ] ''
    $DRY_RUN_CMD rm -f "${heliumThemeDir}/Cached Theme.pak"
  '';
  caelestia.postHooks = [ "rm -f '${heliumThemeDir}/Cached Theme.pak'" ];
}
