# Generated by `nixos-generate-config` for this machine: initrd kernel
# modules and CPU microcode. Not portable — regenerate it on other hardware.
#
# The disk layout (fileSystems, swapDevices, boot.initrd.luks.devices) is
# deliberately not here: disko.nix supplies it. When regenerating, drop
# those parts from the generated file.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
